/*
 * Route Optimization
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routeoptimization.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.routeoptimization.model.PlanSummary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * PlanSummaries
 */
@JsonPropertyOrder({
  PlanSummaries.JSON_PROPERTY_SUMMARIES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-16T11:56:46.561+02:00[Europe/Berlin]")
public class PlanSummaries {
  public static final String JSON_PROPERTY_SUMMARIES = "summaries";
  private List<PlanSummary> summaries = new ArrayList<>();

  public PlanSummaries() { 
  }

  public PlanSummaries summaries(List<PlanSummary> summaries) {
    this.summaries = summaries;
    return this;
  }

  public PlanSummaries addSummariesItem(PlanSummary summariesItem) {
    this.summaries.add(summariesItem);
    return this;
  }

   /**
   * Get summaries
   * @return summaries
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SUMMARIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PlanSummary> getSummaries() {
    return summaries;
  }


  @JsonProperty(JSON_PROPERTY_SUMMARIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSummaries(List<PlanSummary> summaries) {
    this.summaries = summaries;
  }


  /**
   * Return true if this PlanSummaries object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanSummaries planSummaries = (PlanSummaries) o;
    return Objects.equals(this.summaries, planSummaries.summaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(summaries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanSummaries {\n");
    sb.append("    summaries: ").append(toIndentedString(summaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

