/*
 * Route Optimization
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routeoptimization.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import io.swagger.annotations.ApiModel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * If specified, this stop has to be the very first/last customer stop in its trip whenever there is a stop at this location. In each trip, there can only be one stop at a customer location with a trip section of type _FIRST_CUSTOMER_STOP_/_LAST_CUSTOMER_STOP_.    If specified, tripSectionNumber must not be set for the same location.   * &#x60;FIRST_CUSTOMER_STOP&#x60;    A stop at a customer location with this position type has to be the very first customer stop in its trip.   * &#x60;LAST_CUSTOMER_STOP&#x60;    A stop at a customer location with this position type has to be the very last customer stop in its trip.  See [here](./concepts/trip-sections-and-position-trips) for more information.
 */
public enum PositionInTrip {
  
  FIRST_CUSTOMER_STOP("FIRST_CUSTOMER_STOP"),
  
  LAST_CUSTOMER_STOP("LAST_CUSTOMER_STOP");

  private String value;

  PositionInTrip(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PositionInTrip fromValue(String value) {
    for (PositionInTrip b : PositionInTrip.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }
}

