/*
 * Route Optimization
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routeoptimization.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.routeoptimization.model.CapacitiesChangePosition;
import com.ptvgroup.developer.client.routeoptimization.model.TimeInterval;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.routeoptimization.ApiClient;
/**
 * A vehicle that is used to transport goods.
 */
@JsonPropertyOrder({
  Vehicle.JSON_PROPERTY_ID,
  Vehicle.JSON_PROPERTY_CAPACITIES,
  Vehicle.JSON_PROPERTY_ALTERNATIVE_CAPACITIES,
  Vehicle.JSON_PROPERTY_CAPACITIES_CHANGE_POSITION,
  Vehicle.JSON_PROPERTY_EQUIPMENT,
  Vehicle.JSON_PROPERTY_PROFILE,
  Vehicle.JSON_PROPERTY_START_LOCATION_ID,
  Vehicle.JSON_PROPERTY_END_LOCATION_ID,
  Vehicle.JSON_PROPERTY_SERVICE_TIME_PER_TRANSPORT_STOP,
  Vehicle.JSON_PROPERTY_SERVICE_TIME_FACTOR,
  Vehicle.JSON_PROPERTY_IGNORE_MIXED_LOADING_PROHIBITIONS,
  Vehicle.JSON_PROPERTY_ROUTE_START_INTERVAL,
  Vehicle.JSON_PROPERTY_MAXIMUM_DISTANCE,
  Vehicle.JSON_PROPERTY_MAXIMUM_NUMBER_OF_CUSTOMER_STOPS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-27T08:50:35.495306091Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class Vehicle {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_CAPACITIES = "capacities";
  private List<Integer> capacities;

  public static final String JSON_PROPERTY_ALTERNATIVE_CAPACITIES = "alternativeCapacities";
  private List<List<Integer>> alternativeCapacities;

  public static final String JSON_PROPERTY_CAPACITIES_CHANGE_POSITION = "capacitiesChangePosition";
  private CapacitiesChangePosition capacitiesChangePosition = CapacitiesChangePosition.BETWEEN_TRIPS;

  public static final String JSON_PROPERTY_EQUIPMENT = "equipment";
  private List<String> equipment;

  public static final String JSON_PROPERTY_PROFILE = "profile";
  private String profile;

  public static final String JSON_PROPERTY_START_LOCATION_ID = "startLocationId";
  private String startLocationId;

  public static final String JSON_PROPERTY_END_LOCATION_ID = "endLocationId";
  private String endLocationId;

  public static final String JSON_PROPERTY_SERVICE_TIME_PER_TRANSPORT_STOP = "serviceTimePerTransportStop";
  private Integer serviceTimePerTransportStop = 0;

  public static final String JSON_PROPERTY_SERVICE_TIME_FACTOR = "serviceTimeFactor";
  private Double serviceTimeFactor = 1d;

  public static final String JSON_PROPERTY_IGNORE_MIXED_LOADING_PROHIBITIONS = "ignoreMixedLoadingProhibitions";
  private Boolean ignoreMixedLoadingProhibitions = false;

  public static final String JSON_PROPERTY_ROUTE_START_INTERVAL = "routeStartInterval";
  private TimeInterval routeStartInterval;

  public static final String JSON_PROPERTY_MAXIMUM_DISTANCE = "maximumDistance";
  private JsonNullable<Integer> maximumDistance = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_MAXIMUM_NUMBER_OF_CUSTOMER_STOPS = "maximumNumberOfCustomerStops";
  private JsonNullable<Integer> maximumNumberOfCustomerStops = JsonNullable.<Integer>undefined();

  public Vehicle() { 
  }

  public Vehicle id(String id) {
    this.id = id;
    return this;
  }

  /**
   * A unique ID across all vehicles. The ID does not influence the result except the sorting of the routes.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Vehicle capacities(List<Integer> capacities) {
    this.capacities = capacities;
    return this;
  }

  public Vehicle addCapacitiesItem(Integer capacitiesItem) {
    if (this.capacities == null) {
      this.capacities = new ArrayList<>();
    }
    this.capacities.add(capacitiesItem);
    return this;
  }

  /**
   * List of capacities for the different quantity dimensions of goods that can be transported. The maximum length of this list is 100. That is, up to 100 different quantity dimensions (e.g. number of pallets, weight, volume, etc.) can be distinguished. Transports can only be executed by a vehicle with a higher (or an equal) maximum capacity in every quantity dimension. The length of this list has to be the same for all transports and all vehicles. If and only if this list of capacities is empty for all vehicles, the quantities of each transport must be empty.
   * @return capacities
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPACITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Integer> getCapacities() {
    return capacities;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacities(List<Integer> capacities) {
    this.capacities = capacities;
  }


  public Vehicle alternativeCapacities(List<List<Integer>> alternativeCapacities) {
    this.alternativeCapacities = alternativeCapacities;
    return this;
  }

  public Vehicle addAlternativeCapacitiesItem(List<Integer> alternativeCapacitiesItem) {
    if (this.alternativeCapacities == null) {
      this.alternativeCapacities = new ArrayList<>();
    }
    this.alternativeCapacities.add(alternativeCapacitiesItem);
    return this;
  }

  /**
   * List of alternative capacities. Each entry in this array must be valid capacities, more details are described in **capacities**. If a route cannot be driven with the **capacities**, alternative capacities may be chosen by the optimization considering the chosen **capacitiesChangePosition**.  See [here](./concepts/capacities-and-alternative-capacities) for more information.
   * @return alternativeCapacities
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALTERNATIVE_CAPACITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<List<Integer>> getAlternativeCapacities() {
    return alternativeCapacities;
  }


  @JsonProperty(JSON_PROPERTY_ALTERNATIVE_CAPACITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlternativeCapacities(List<List<Integer>> alternativeCapacities) {
    this.alternativeCapacities = alternativeCapacities;
  }


  public Vehicle capacitiesChangePosition(CapacitiesChangePosition capacitiesChangePosition) {
    this.capacitiesChangePosition = capacitiesChangePosition;
    return this;
  }

  /**
   * Get capacitiesChangePosition
   * @return capacitiesChangePosition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPACITIES_CHANGE_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CapacitiesChangePosition getCapacitiesChangePosition() {
    return capacitiesChangePosition;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITIES_CHANGE_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacitiesChangePosition(CapacitiesChangePosition capacitiesChangePosition) {
    this.capacitiesChangePosition = capacitiesChangePosition;
  }


  public Vehicle equipment(List<String> equipment) {
    this.equipment = equipment;
    return this;
  }

  public Vehicle addEquipmentItem(String equipmentItem) {
    if (this.equipment == null) {
      this.equipment = new ArrayList<>();
    }
    this.equipment.add(equipmentItem);
    return this;
  }

  /**
   * List of vehicle equipment. A transport can only be served by the vehicle if this list is a superset of (or equal to) the transport&#39;s required vehicle equipment.
   * @return equipment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getEquipment() {
    return equipment;
  }


  @JsonProperty(JSON_PROPERTY_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquipment(List<String> equipment) {
    this.equipment = equipment;
  }


  public Vehicle profile(String profile) {
    this.profile = profile;
    return this;
  }

  /**
   * The profile defines attributes of the vehicle relevant to determine travel times and distances between any two locations. See [here](./concepts/profiles-and-countries) for a complete list of allowed values. If the majority of locations are in the Americas, _USA_8_SEMITRAILER_5AXLE_ is used as the default. Otherwise, _EUR_TRAILER_TRUCK_ is used as the default.  If most locations are located in the Americas but a non-American vehicle profile is specified or vice-versa, a warning is returned. Always use a vehicle profile which matches the region of the locations to obtain best results.
   * @return profile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProfile() {
    return profile;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfile(String profile) {
    this.profile = profile;
  }


  public Vehicle startLocationId(String startLocationId) {
    this.startLocationId = startLocationId;
    return this;
  }

  /**
   * ID of the vehicle&#39;s start location. If the vehicle start location does not coincide with the location of the first pickup, only the coordinates of the vehicle start location are considered and all other attributes such as opening intervals, service time or type are ignored. If no start location is specified, it is assumed that the vehicle is available at the first stop.
   * @return startLocationId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStartLocationId() {
    return startLocationId;
  }


  @JsonProperty(JSON_PROPERTY_START_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartLocationId(String startLocationId) {
    this.startLocationId = startLocationId;
  }


  public Vehicle endLocationId(String endLocationId) {
    this.endLocationId = endLocationId;
    return this;
  }

  /**
   * ID of the vehicle&#39;s end location. If the vehicle end location does not coincide with the location of the last delivery, only the coordinates of the vehicle end location are considered and all other attributes such as opening intervals, service time or type are ignored. If no end location is specified, it is assumed that the vehicle remains at the last stop.
   * @return endLocationId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEndLocationId() {
    return endLocationId;
  }


  @JsonProperty(JSON_PROPERTY_END_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndLocationId(String endLocationId) {
    this.endLocationId = endLocationId;
  }


  public Vehicle serviceTimePerTransportStop(Integer serviceTimePerTransportStop) {
    this.serviceTimePerTransportStop = serviceTimePerTransportStop;
    return this;
  }

  /**
   * Vehicle-dependent service time [s], for example, for maneuvering. This service time is taken into account for each stop served by this vehicle to pick up or deliver goods. Besides a vehicle-dependent service time, the user may specify location- and transport-dependent service times at the locations and the transports respectively.
   * minimum: 0
   * @return serviceTimePerTransportStop
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_TIME_PER_TRANSPORT_STOP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getServiceTimePerTransportStop() {
    return serviceTimePerTransportStop;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_TIME_PER_TRANSPORT_STOP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceTimePerTransportStop(Integer serviceTimePerTransportStop) {
    this.serviceTimePerTransportStop = serviceTimePerTransportStop;
  }


  public Vehicle serviceTimeFactor(Double serviceTimeFactor) {
    this.serviceTimeFactor = serviceTimeFactor;
    return this;
  }

  /**
   * A factor that scales transport-dependent service times of all transport-related service actions, for example, if loading and unloading is more or less complicated than for other vehicles. A factor less than one means that the vehicle speeds up the service, a factor greater than one means that it slows the service down.
   * minimum: 0.1
   * maximum: 10
   * @return serviceTimeFactor
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_TIME_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Double getServiceTimeFactor() {
    return serviceTimeFactor;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_TIME_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceTimeFactor(Double serviceTimeFactor) {
    this.serviceTimeFactor = serviceTimeFactor;
  }


  public Vehicle ignoreMixedLoadingProhibitions(Boolean ignoreMixedLoadingProhibitions) {
    this.ignoreMixedLoadingProhibitions = ignoreMixedLoadingProhibitions;
    return this;
  }

  /**
   * Indicates whether the mixed loading prohibitions are relevant for this vehicle. If set to false, the mixed loading prohibitions -- if there are any -- must be respected on every trip of the vehicle. If set to true, the mixed loading prohibitions are ignored by the vehicle.
   * @return ignoreMixedLoadingProhibitions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IGNORE_MIXED_LOADING_PROHIBITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIgnoreMixedLoadingProhibitions() {
    return ignoreMixedLoadingProhibitions;
  }


  @JsonProperty(JSON_PROPERTY_IGNORE_MIXED_LOADING_PROHIBITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIgnoreMixedLoadingProhibitions(Boolean ignoreMixedLoadingProhibitions) {
    this.ignoreMixedLoadingProhibitions = ignoreMixedLoadingProhibitions;
  }


  public Vehicle routeStartInterval(TimeInterval routeStartInterval) {
    this.routeStartInterval = routeStartInterval;
    return this;
  }

  /**
   * Interval in which the vehicle has to start its route. Start and end of the interval may be the same. Leaving this parameter empty means that the route start is unrestricted.
   * @return routeStartInterval
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROUTE_START_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TimeInterval getRouteStartInterval() {
    return routeStartInterval;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_START_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRouteStartInterval(TimeInterval routeStartInterval) {
    this.routeStartInterval = routeStartInterval;
  }


  public Vehicle maximumDistance(Integer maximumDistance) {
    this.maximumDistance = JsonNullable.<Integer>of(maximumDistance);
    return this;
  }

  /**
   * Restricts the maximum allowed total driving distance [m] for the route of this vehicle.
   * @return maximumDistance
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getMaximumDistance() {
        return maximumDistance.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MAXIMUM_DISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getMaximumDistance_JsonNullable() {
    return maximumDistance;
  }
  
  @JsonProperty(JSON_PROPERTY_MAXIMUM_DISTANCE)
  public void setMaximumDistance_JsonNullable(JsonNullable<Integer> maximumDistance) {
    this.maximumDistance = maximumDistance;
  }

  public void setMaximumDistance(Integer maximumDistance) {
    this.maximumDistance = JsonNullable.<Integer>of(maximumDistance);
  }


  public Vehicle maximumNumberOfCustomerStops(Integer maximumNumberOfCustomerStops) {
    this.maximumNumberOfCustomerStops = JsonNullable.<Integer>of(maximumNumberOfCustomerStops);
    return this;
  }

  /**
   * Restricts the maximum allowed total number of customer stops, i.e. stops at customer locations, for the route of this vehicle.
   * @return maximumNumberOfCustomerStops
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getMaximumNumberOfCustomerStops() {
        return maximumNumberOfCustomerStops.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MAXIMUM_NUMBER_OF_CUSTOMER_STOPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getMaximumNumberOfCustomerStops_JsonNullable() {
    return maximumNumberOfCustomerStops;
  }
  
  @JsonProperty(JSON_PROPERTY_MAXIMUM_NUMBER_OF_CUSTOMER_STOPS)
  public void setMaximumNumberOfCustomerStops_JsonNullable(JsonNullable<Integer> maximumNumberOfCustomerStops) {
    this.maximumNumberOfCustomerStops = maximumNumberOfCustomerStops;
  }

  public void setMaximumNumberOfCustomerStops(Integer maximumNumberOfCustomerStops) {
    this.maximumNumberOfCustomerStops = JsonNullable.<Integer>of(maximumNumberOfCustomerStops);
  }


  /**
   * Return true if this Vehicle object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vehicle vehicle = (Vehicle) o;
    return Objects.equals(this.id, vehicle.id) &&
        Objects.equals(this.capacities, vehicle.capacities) &&
        Objects.equals(this.alternativeCapacities, vehicle.alternativeCapacities) &&
        Objects.equals(this.capacitiesChangePosition, vehicle.capacitiesChangePosition) &&
        Objects.equals(this.equipment, vehicle.equipment) &&
        Objects.equals(this.profile, vehicle.profile) &&
        Objects.equals(this.startLocationId, vehicle.startLocationId) &&
        Objects.equals(this.endLocationId, vehicle.endLocationId) &&
        Objects.equals(this.serviceTimePerTransportStop, vehicle.serviceTimePerTransportStop) &&
        Objects.equals(this.serviceTimeFactor, vehicle.serviceTimeFactor) &&
        Objects.equals(this.ignoreMixedLoadingProhibitions, vehicle.ignoreMixedLoadingProhibitions) &&
        Objects.equals(this.routeStartInterval, vehicle.routeStartInterval) &&
        equalsNullable(this.maximumDistance, vehicle.maximumDistance) &&
        equalsNullable(this.maximumNumberOfCustomerStops, vehicle.maximumNumberOfCustomerStops);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, capacities, alternativeCapacities, capacitiesChangePosition, equipment, profile, startLocationId, endLocationId, serviceTimePerTransportStop, serviceTimeFactor, ignoreMixedLoadingProhibitions, routeStartInterval, hashCodeNullable(maximumDistance), hashCodeNullable(maximumNumberOfCustomerStops));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vehicle {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    capacities: ").append(toIndentedString(capacities)).append("\n");
    sb.append("    alternativeCapacities: ").append(toIndentedString(alternativeCapacities)).append("\n");
    sb.append("    capacitiesChangePosition: ").append(toIndentedString(capacitiesChangePosition)).append("\n");
    sb.append("    equipment: ").append(toIndentedString(equipment)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    startLocationId: ").append(toIndentedString(startLocationId)).append("\n");
    sb.append("    endLocationId: ").append(toIndentedString(endLocationId)).append("\n");
    sb.append("    serviceTimePerTransportStop: ").append(toIndentedString(serviceTimePerTransportStop)).append("\n");
    sb.append("    serviceTimeFactor: ").append(toIndentedString(serviceTimeFactor)).append("\n");
    sb.append("    ignoreMixedLoadingProhibitions: ").append(toIndentedString(ignoreMixedLoadingProhibitions)).append("\n");
    sb.append("    routeStartInterval: ").append(toIndentedString(routeStartInterval)).append("\n");
    sb.append("    maximumDistance: ").append(toIndentedString(maximumDistance)).append("\n");
    sb.append("    maximumNumberOfCustomerStops: ").append(toIndentedString(maximumNumberOfCustomerStops)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `capacities` to the URL query string
    if (getCapacities() != null) {
      for (int i = 0; i < getCapacities().size(); i++) {
        joiner.add(String.format("%scapacities%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getCapacities().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `alternativeCapacities` to the URL query string
    if (getAlternativeCapacities() != null) {
      for (int i = 0; i < getAlternativeCapacities().size(); i++) {
        joiner.add(String.format("%salternativeCapacities%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getAlternativeCapacities().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `capacitiesChangePosition` to the URL query string
    if (getCapacitiesChangePosition() != null) {
      joiner.add(String.format("%scapacitiesChangePosition%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCapacitiesChangePosition()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `equipment` to the URL query string
    if (getEquipment() != null) {
      for (int i = 0; i < getEquipment().size(); i++) {
        joiner.add(String.format("%sequipment%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getEquipment().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `profile` to the URL query string
    if (getProfile() != null) {
      joiner.add(String.format("%sprofile%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getProfile()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `startLocationId` to the URL query string
    if (getStartLocationId() != null) {
      joiner.add(String.format("%sstartLocationId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getStartLocationId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `endLocationId` to the URL query string
    if (getEndLocationId() != null) {
      joiner.add(String.format("%sendLocationId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEndLocationId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `serviceTimePerTransportStop` to the URL query string
    if (getServiceTimePerTransportStop() != null) {
      joiner.add(String.format("%sserviceTimePerTransportStop%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getServiceTimePerTransportStop()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `serviceTimeFactor` to the URL query string
    if (getServiceTimeFactor() != null) {
      joiner.add(String.format("%sserviceTimeFactor%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getServiceTimeFactor()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `ignoreMixedLoadingProhibitions` to the URL query string
    if (getIgnoreMixedLoadingProhibitions() != null) {
      joiner.add(String.format("%signoreMixedLoadingProhibitions%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getIgnoreMixedLoadingProhibitions()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `routeStartInterval` to the URL query string
    if (getRouteStartInterval() != null) {
      joiner.add(getRouteStartInterval().toUrlQueryString(prefix + "routeStartInterval" + suffix));
    }

    // add `maximumDistance` to the URL query string
    if (getMaximumDistance() != null) {
      joiner.add(String.format("%smaximumDistance%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMaximumDistance()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `maximumNumberOfCustomerStops` to the URL query string
    if (getMaximumNumberOfCustomerStops() != null) {
      joiner.add(String.format("%smaximumNumberOfCustomerStops%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMaximumNumberOfCustomerStops()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

