/*
 * Route Optimization
 *
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.8
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.Model
{
    /// <summary>
    /// Position where the **capacities** or **alternativeCapacities** of the vehicle may be changed.
    /// </summary>
    /// <value>Position where the **capacities** or **alternativeCapacities** of the vehicle may be changed.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CapacitiesChangePosition
    {
        /// <summary>
        /// Enum BETWEEN_TRIPS for value: BETWEEN_TRIPS
        /// </summary>
        [EnumMember(Value = "BETWEEN_TRIPS")]
        BETWEEN_TRIPS = 1,

        /// <summary>
        /// Enum AT_STOP for value: AT_STOP
        /// </summary>
        [EnumMember(Value = "AT_STOP")]
        AT_STOP = 2

    }

}
