/*
 * Route Optimization
 *
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.7
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.Model
{
    /// <summary>
    /// Indicates at which position of a route daily rests are planned.  See [here](./concepts/drivers-working-hours-break-and-rest-rules) for more information.
    /// </summary>
    /// <value>Indicates at which position of a route daily rests are planned.  See [here](./concepts/drivers-working-hours-break-and-rest-rules) for more information.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DailyRestPosition
    {
        /// <summary>
        /// Enum BETWEEN_TRIPS for value: BETWEEN_TRIPS
        /// </summary>
        [EnumMember(Value = "BETWEEN_TRIPS")]
        BETWEEN_TRIPS = 1,

        /// <summary>
        /// Enum ANYWHERE for value: ANYWHERE
        /// </summary>
        [EnumMember(Value = "ANYWHERE")]
        ANYWHERE = 2

    }

}
