/*
 * Route Optimization
 *
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.Model
{
    /// <summary>
    /// PlanSummaries
    /// </summary>
    [DataContract(Name = "PlanSummaries")]
    public partial class PlanSummaries : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanSummaries" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlanSummaries() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanSummaries" /> class.
        /// </summary>
        /// <param name="summaries">summaries (required).</param>
        public PlanSummaries(List<PlanSummary> summaries = default(List<PlanSummary>))
        {
            // to ensure "summaries" is required (not null)
            if (summaries == null)
            {
                throw new ArgumentNullException("summaries is a required property for PlanSummaries and cannot be null");
            }
            this.Summaries = summaries;
        }

        /// <summary>
        /// Gets or Sets Summaries
        /// </summary>
        [DataMember(Name = "summaries", IsRequired = true, EmitDefaultValue = true)]
        public List<PlanSummary> Summaries { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlanSummaries {\n");
            sb.Append("  Summaries: ").Append(Summaries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
