/*
 * Route Optimization
 *
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.8
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routeoptimization.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routeoptimization.Model
{
    /// <summary>
    /// A tweak to objective defines additional optimization criteria. Without any tweak, the standard optimization goal is to plan as many transports as possible with as few vehicles as possible.   * &#x60;AVOID_INTERSECTIONS&#x60; - The focus of this approach is to avoid intersections of edges, where an edge is a straight line drawn between two consecutive stops in a route. The number of routes may be higher compared to the standard optimization goal.   * &#x60;IGNORE_MINIMIZATION_OF_NUMBER_OF_ROUTES&#x60; - With this tweak, the number of vehicles used in a plan, and thus the number of routes, is not minimized.
    /// </summary>
    /// <value>A tweak to objective defines additional optimization criteria. Without any tweak, the standard optimization goal is to plan as many transports as possible with as few vehicles as possible.   * &#x60;AVOID_INTERSECTIONS&#x60; - The focus of this approach is to avoid intersections of edges, where an edge is a straight line drawn between two consecutive stops in a route. The number of routes may be higher compared to the standard optimization goal.   * &#x60;IGNORE_MINIMIZATION_OF_NUMBER_OF_ROUTES&#x60; - With this tweak, the number of vehicles used in a plan, and thus the number of routes, is not minimized.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TweakToObjective
    {
        /// <summary>
        /// Enum AVOID_INTERSECTIONS for value: AVOID_INTERSECTIONS
        /// </summary>
        [EnumMember(Value = "AVOID_INTERSECTIONS")]
        AVOID_INTERSECTIONS = 1,

        /// <summary>
        /// Enum IGNORE_MINIMIZATION_OF_NUMBER_OF_ROUTES for value: IGNORE_MINIMIZATION_OF_NUMBER_OF_ROUTES
        /// </summary>
        [EnumMember(Value = "IGNORE_MINIMIZATION_OF_NUMBER_OF_ROUTES")]
        IGNORE_MINIMIZATION_OF_NUMBER_OF_ROUTES = 2

    }

}
