/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PositionInTrip,
    PositionInTripFromJSON,
    PositionInTripFromJSONTyped,
    PositionInTripToJSON,
} from './PositionInTrip';

/**
 * Attributes for a location of type CUSTOMER.
 * @export
 * @interface CustomerLocationAttributes
 */
export interface CustomerLocationAttributes {
    /**
     * 
     * @type {PositionInTrip}
     * @memberof CustomerLocationAttributes
     */
    positionInTrip?: PositionInTrip | null;
    /**
     * If tripSectionNumber is specified, a stop at this customer location will be visited after stops (within the same trip) at customer locations with specified lower tripSectionNumber and before stops (within the same trip) at customer locations with specified higher tripSectionNumber. Consequently, the trip section numbers of stops at customer locations must be non-decreasing within each trip. 
     * 
     * If specified, positionInTrip must not be set for the same location.
     * 
     * See [here](./concepts/trip-sections-and-position-trips) for more information.
     * @type {number}
     * @memberof CustomerLocationAttributes
     */
    tripSectionNumber?: number | null;
}

export function CustomerLocationAttributesFromJSON(json: any): CustomerLocationAttributes {
    return CustomerLocationAttributesFromJSONTyped(json, false);
}

export function CustomerLocationAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerLocationAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'positionInTrip': !exists(json, 'positionInTrip') ? undefined : PositionInTripFromJSON(json['positionInTrip']),
        'tripSectionNumber': !exists(json, 'tripSectionNumber') ? undefined : json['tripSectionNumber'],
    };
}

export function CustomerLocationAttributesToJSON(value?: CustomerLocationAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'positionInTrip': PositionInTripToJSON(value.positionInTrip),
        'tripSectionNumber': value.tripSectionNumber,
    };
}

