/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OptimizationQuality = {
    STANDARD: 'STANDARD',
    HIGH: 'HIGH'
} as const;
export type OptimizationQuality = typeof OptimizationQuality[keyof typeof OptimizationQuality];


export function instanceOfOptimizationQuality(value: any): boolean {
    for (const key in OptimizationQuality) {
        if (Object.prototype.hasOwnProperty.call(OptimizationQuality, key)) {
            if (OptimizationQuality[key as keyof typeof OptimizationQuality] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OptimizationQualityFromJSON(json: any): OptimizationQuality {
    return OptimizationQualityFromJSONTyped(json, false);
}

export function OptimizationQualityFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimizationQuality {
    return json as OptimizationQuality;
}

export function OptimizationQualityToJSON(value?: OptimizationQuality | null): any {
    return value as any;
}

export function OptimizationQualityToJSONTyped(value: any, ignoreDiscriminator: boolean): OptimizationQuality {
    return value as OptimizationQuality;
}

