/* tslint:disable */
/* eslint-disable */
/**
 * Route Optimization
 * With the Route Optimization service you can schedule and optimize the routes of your fleet.
 *
 * The version of the OpenAPI document: 1.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanSummary } from './PlanSummary';
import {
    PlanSummaryFromJSON,
    PlanSummaryFromJSONTyped,
    PlanSummaryToJSON,
    PlanSummaryToJSONTyped,
} from './PlanSummary';

/**
 * 
 * @export
 * @interface PlanSummaries
 */
export interface PlanSummaries {
    /**
     * 
     * @type {Array<PlanSummary>}
     * @memberof PlanSummaries
     */
    summaries: Array<PlanSummary>;
}

/**
 * Check if a given object implements the PlanSummaries interface.
 */
export function instanceOfPlanSummaries(value: object): value is PlanSummaries {
    if (!('summaries' in value) || value['summaries'] === undefined) return false;
    return true;
}

export function PlanSummariesFromJSON(json: any): PlanSummaries {
    return PlanSummariesFromJSONTyped(json, false);
}

export function PlanSummariesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanSummaries {
    if (json == null) {
        return json;
    }
    return {
        
        'summaries': ((json['summaries'] as Array<any>).map(PlanSummaryFromJSON)),
    };
}

  export function PlanSummariesToJSON(json: any): PlanSummaries {
      return PlanSummariesToJSONTyped(json, false);
  }

  export function PlanSummariesToJSONTyped(value?: PlanSummaries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summaries': ((value['summaries'] as Array<any>).map(PlanSummaryToJSON)),
    };
}

